name: 3Dify CI
on:
  push:
    branches:
      - master
      - developp
  pull_request:
    branches:
      - master
      - developp

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Cache Maven dependencies
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check Coding Style
        run: mvn checkstyle:check

  build_Test_CodeCoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Cache Maven dependencies
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn package -DskipTests

      - name: Tests
        run: mvn test
        
      - name: Generate_Code_Coverage_report
        run: mvn jacoco:report
        
      - name: Upload_To_CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: ./codecov.yml


